version: '3'

services:
  db:
    image: postgres
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
  api:
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 8000:3000
    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./front:/app
    command: ["yarn", "start"]
    ports:
      - 8001:3000

volumes:
  db-store:
